//配置依赖文件
require.config({
	//各文件路径
	paths:{
		jquery:'../lib/jquery-1.11.1.min',
		commom:'./common',
		echarts:'../lib/echarts',
		bootstrap:'../lib/bootstrap.min'
	},
	shim:{
		bootstrap:['jquery'],
		commom:['jquery']
	}
})